feign:
  compression:
    request: 
      enabled: true
    response:
      enabled: true
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  rabbitmq:
      host: 203.195.250.141
      port: 5672
      username: java
      password: 123
      virtual-host: /java19
